apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-onlineretailer-order-hpa
spec:
  maxReplicas: 4 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orderapi
  targetCPUUtilizationPercentage: 50 # target CPU utilization

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-onlineretailer-product-hpa
spec:
  maxReplicas: 4 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productapi
  targetCPUUtilizationPercentage: 50 # target CPU utilization

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-onlineretailer-customer-hpa
spec:
  maxReplicas: 4 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customerapi
  targetCPUUtilizationPercentage: 50 # target CPU utilization