apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi
        image: domco545/customerapi:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: customerapi
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: customerapi
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 8081
    nodePort: 30010